CREATE TABLE "JAVADB"."MEMBER2" (
    "ID"         VARCHAR2(10 BYTE)
        NOT NULL ENABLE,
    "PASSWORD"   VARCHAR2(10 BYTE)
        NOT NULL ENABLE,
    "NAME"       VARCHAR2(10 BYTE)
        NOT NULL ENABLE,
    "AGE"        NUMBER,
    "ADDR"       VARCHAR2(50 BYTE),
    "EMAIL"      VARCHAR2(30 BYTE),
    PRIMARY KEY ( "ID" )
        USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
            DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "USERS"
    ENABLE
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL
    DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";